steps:
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_8_PLUS'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_X'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_X"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_SE'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_SE"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_6'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_6"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_6S'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_6S"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPHONE_6S_PLUS'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_6S_PLUS"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPAD_5TH'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPAD_5TH"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPAD_MINI_4'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPAD_MINI_4"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPAD_PRO_9_7_2016'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPAD_PRO_9_7_2016"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPAD_6TH'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPAD_6TH"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 11 end-to-end tests - IOS_11_0_IPAD_PRO_12_9'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPAD_PRO_12_9"
          - "--appium-version=1.7.0"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
