steps:
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: iOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-alex-117
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "13.7"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: ':apple: macOS 10.15 barebones end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-alex-167
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
