steps:
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: ':apple: macOS 11.0 barebones end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-alex-test
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --farm=local
        --os=macos
        --os-version=11.0
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        --verbose
