
  - label: 'Update documentation page'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/ && build.branch == "master"
    agents:
      queue: opensource-mac-cocoa
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    command:
      - make update-docs
