steps:
  - label: macOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "macOS"
    commands:
      - make bootstrap
      - make analyze test

  - label: macOS 10.14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "macOS"
    commands:
      - make bootstrap
      - make analyze test

  - label: iOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "13.7"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "12.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "11.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "10.3.1"
      DEVICE: "iPhone 5s"
    commands:
      - make bootstrap
      - make test

  - label: tvOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "13.3"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "12.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "11.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "10.2"
    commands:
      - make bootstrap
      - make test

